### PR TITLE
enh: uses packagingExclude / include for war:exploded

### LINKED ISSUE #554: war:exploded goal does not respect <packagingExcludes> directive
### Affected version

Latest

### Bug description

`war:war` goal supports `<packagingExcludes>` etc. directives.
It looks like `war:exploded` doesn't. This is preventing from generating thin exploded WARs.
Is this an oversight?

### PR DESCRIPTION
**Pull request by lprimak**
## This is a fix for a missing feature

The plugin is enhanced to take `<packagingExcludes>` and `<packagingIncludes>` parameters into account when executing `war:exploded` and `war:inplace` goals in addition to just `war:war` goal previously

## What are the changes?
- moved `packagingExcludes` and `packagingIncludes` parameters into `AbstractWarMojo` from `WarMojo`
- added `getPackagingExcludes()` and `getPackagingIncludes()` to `WarPackagingContext` interface
- added `isExcluded()` method to `copyFile()` to filter out files

Fixes #554 

Following this checklist to help us incorporate your
contribution quickly and easily:

- [x] Your pull request should address just one issue, without pulling in other changes.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Each commit in the pull request should have a meaningful subject line and body.
  Note that commits might be squashed by a maintainer on merge.
- [ ] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied.
  This may not always be possible but is a best-practice.
- [x] Run `mvn verify` to make sure basic checks pass.
  A more thorough check will be performed on your pull request automatically.
- [x] You have run the integration tests successfully (`mvn -Prun-its verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

File: src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java [hunk 1]
```diff
@@ -230,6 +230,26 @@ public abstract class AbstractWarMojo extends AbstractMojo {
     @Parameter
     private String dependentWarExcludes = StringUtils.join(Overlay.DEFAULT_EXCLUDES, ",");
 
+    /**
+     * The comma separated list of tokens to exclude from the WAR before packaging. This option may be used to implement
+     * the skinny WAR use case. Note that you can use the Java Regular Expressions engine to include and exclude
+     * specific pattern using the expression %regex[]. Hint: read the about (?!Pattern).
+     *
+     * @since 2.1-alpha-2
```
Comment (slawekjaranowski) [inline src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java:238]: `3.4.1`?

File: src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java [hunk 2]
```diff
@@ -230,6 +230,26 @@ public abstract class AbstractWarMojo extends AbstractMojo {
...
+     */
+    @Parameter(property = "maven.war.packagingExcludes")
+    private String packagingExcludes;
```
Comment (slawekjaranowski) [inline src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java:241]: Can be `List<String>` rest of code can be simplified
we can still use comma separated list for property

File: src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java (hunk 1 above)
Comment (lprimak) [reply src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java:238]: This was moved, not added, so `@since` is correct here

File: src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java [hunk 3]
```diff
@@ -230,6 +230,26 @@ public abstract class AbstractWarMojo extends AbstractMojo {
...
+
+    /**
+     * The comma separated list of tokens to include in the WAR before packaging. By default everything is included.
+     * This option may be used to implement the skinny WAR use case. Note that you can use the Java Regular Expressions
+     * engine to include and exclude specific pattern using the expression %regex[].
+     *
+     * @since 2.1-beta-1
+     */
+    @Parameter
+    private String packagingIncludes;
```
Comment (slawekjaranowski) [inline src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java:251]: `List<String>`

Comment (lprimak) [reply src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java:251]: this was moved, same :)

File: src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java [hunk 4]
```diff
@@ -230,6 +230,26 @@ public abstract class AbstractWarMojo extends AbstractMojo {
...
+    private String packagingExcludes;
+
+    /**
+     * The comma separated list of tokens to include in the WAR before packaging. By default everything is included.
+     * This option may be used to implement the skinny WAR use case. Note that you can use the Java Regular Expressions
+     * engine to include and exclude specific pattern using the expression %regex[].
+     *
+     * @since 2.1-beta-1
+     */
+    @Parameter
```
[the remark this answers is not in the document]
Comment (lprimak) [reply src/main/java/org/apache/maven/plugins/war/AbstractWarMojo.java:250]: same

**Comment by lprimak** [comment]
I guess the question is do you want me to add improvements to the plugin, not just minimum changes required to fix the bug?

**Comment by slawekjaranowski** [comment]
> I guess the question is do you want me to add improvements to the plugin, not just minimum changes required to fix the bug?

Ok, I see - code is moved.

So I will not required improvements - but it will be nice to have

But some test should be added

**Comment by lprimak** [comment]
Thanks @slawekjaranowski This would have taken me forever to figure out!

**Comment by lprimak** [comment]
Thank you Slawomir! Hope to see 3.4.1 release soon as this is holding things back for me.

**Comment by pzygielo** [comment]
- https://github.com/apache/maven-war-plugin/issues/577
